### ISSUE TITLE
AVX2 SAD has wrong return type

### ISSUE THREAD

**Issue by the8472** [hsivonen/simd#18]
https://github.com/rust-lang-nursery/simd/blob/539247c63cd59dc3aac973c02a86845674ee3b6a/src/x86/avx2.rs#L45

`fn x86_mm256_sad_epu8(x: u8x32, y: u8x32)  -> u8x32` 
should be
`fn x86_mm256_sad_epu8(x: u8x32, y: u8x32)  -> u64x4`

The [intel intrinsics docs](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=AVX,AVX2&expand=2800,362,4676,4678,2880,532,533,4726,4535&text=sad) state that the result is packed into 4x 64bit values.

I tried fixing it myself but the compiler then complains

```
error[E0442]: intrinsic return value has wrong type: found vector with length 4, expected length 32
  --> src/x86/avx2.rs:45:5
   |
45 |     fn x86_mm256_sad_epu8(x: u8x32, y: u8x32) -> u64x4;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by BurntSushi** [comment]
The intrinsic definition in LLVM is:

```
  def int_x86_avx2_psad_bw : GCCBuiltin<"__builtin_ia32_psadbw256">,
              Intrinsic<[llvm_v4i64_ty], [llvm_v32i8_ty,
                         llvm_v32i8_ty], [IntrNoMem, Commutative]>;
```

Which appears consistent with the Intel intrinsic docs. The next place I'd look is in `rustc` to see if there's a bug in the corresponding `platform-intrinsic`. Indeed, the [definition appears incorrect](https://github.com/rust-lang/rust/blob/152055451c552121be35a179bb77194e02800baa/src/etc/platform-intrinsics/x86/avx2.json#L173-L179), so I think this needs to be filed against rust-lang/rust.

**Comment by the8472** [comment]
Filed rust-lang/rust#43439
