### ISSUE TITLE
Documentation (link in README.md?) is broken

### ISSUE THREAD

**Issue by palotasb** [hsivonen/simd#23]
Current link: https://docs.rs/simd
Redirects to: https://docs.rs/simd/0.2.1/simd/ ("The requested resource does not exist")
Correct link I assume should be: https://docs.rs/crate/simd/

**Comment by palotasb** [comment]
It could also be a rustdoc error?

On the last link above:
> docs.rs failed to build simd-0.2.1
> Please check build logs and if you believe this is docs.rs' fault, report into this issue report.

Build log: https://docs.rs/crate/simd/0.2.1/builds/80899

**Comment by hsivonen** [comment]
> ("The requested resource does not exist")

This appears to have been fixed.
